version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.3
  lambroll: fujiwara/lambroll@dev:2019-11-06-12-11

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - lambroll/install
      - run: |
          cd hello && make deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
