version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.3
  lambroll: fujiwara/lambroll@0.0.7
  ecspresso: fujiwara/ecspresso@0.0.14

jobs:
  install:
    docker:
      - image: cimg/base:2020.12
    steps:
      - checkout
      - ecspresso/install:
          version: latest
      - run:
          command: |
            ecspresso version
      - ecspresso/install:
          version: v1.5.0
      - run:
          command: |
            ecspresso version
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - lambroll/install
      - run: |
          cd hello && make deploy

workflows:
  version: 2
  deploy:
    jobs:
      - install:
          filters:
            branches:
              only:
                - master
