version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.3
  lambroll: fujiwara/lambroll@dev:latest
  ecspresso: fujiwara/ecspresso@0.0.11

jobs:
  install:
    steps:
      - checkout
      - ecspresso/install:
          version: 1.1.3
      - run:
          command: |
            ecspresso version
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - lambroll/install
      - run: |
          cd hello && make deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
