version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  lambroll: fujiwara/lambroll@1.0.0
  ecspresso: fujiwara/ecspresso@2.0.3

jobs:
  install:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - ecspresso/install:
          version: v2.3.2
      - run:
          command: |
            ecspresso version
      - lambroll/install:
          version: v1.0.0-rc2
      - run:
          command: |
            lambroll version
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - lambroll/install
      - run: |
          cd hello && make deploy

workflows:
  version: 2
  deploy:
    jobs:
      - install:
          filters:
            branches:
              only:
                - master
