version: 2.1

orbs:
  detect: circleci/os-detect@0.1
  aws-cli: circleci/aws-cli@0.1.3
  lambroll: fujiwara/lambroll@0.0.5

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - detect/init
      - aws-cli/install
      - aws-cli/configure
      - lambroll/install
      - run: |
          cd hello && make deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
