name: install
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fujiwara/lambroll@v0
        with:
          version: v0.9.1
      - run: |
          which lambroll
          file $(which lambroll)
          lambroll version
          lambroll --help
