name: install
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fujiwara/lambroll@v1
        with:
          version: v1.0.0-rc2
      - uses: kayac/ecspresso@v1
        with:
          version: latest
      - run: |
          which lambroll
          file $(which lambroll)
          lambroll version
          lambroll --help
      - run: |
          which ecspresso
          file $(which ecspresso)
          ecspresso version
          ecspresso --help
